import Head from 'next/head'
import Header from '../components/Header'
import { getSession } from "next-auth/client"
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';

export default function Home() {
  return (
    <div className="h-screen overflow-hidden bg-gray-100">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex">
          <Sidebar />
          <Feed />
      </main>
    </div>
  )
}

